name: Makefile CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
          ref: trunk
    - name: Build using Nmake
      shell: cmd
      run: |
            echo on
            call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=${{ matrix.arch }}
            cd native
            echo "Building for ${{ matrix.arch }}"
            nmake BUILD_CPU=${{ matrix.arch }}
